
import java.util.Random;

public class Random_num {
  public int[] generate4DigitRandomArray(int size){
    int[] numbers = new int[size] ;
    Random random = new Random() ;//random object created 
    
    for (int i = 0; i < numbers.length; i++) {
      numbers[i] = 1000 + random.nextInt(9000) ; //four-digit no. generated by keeping the UB strictly below 9000..
    }
    return numbers ; 
  }

  public double findAverageMinMax(int[] numbers) {
    int max = Integer.MIN_VALUE; 
    int min = Integer.MAX_VALUE ; 
    double sum = 0 ;

    for (int i = 0; i < numbers.length; i++) {
      max = Math.max(max, numbers[i]) ; 
      min = Math.min(min, numbers[i]) ;  
      sum += numbers[i]; 
    }

    return sum/numbers.length;
  }
  public static void main(String[] args) {
    Random_num rm = new Random_num() ; 

    int [] result = rm.generate4DigitRandomArray(4) ; 

    for (int i = 0; i < result.length; i++) {
      System.out.print(result[i]+" ");
    }

    System.out.println("\nAvg: "+ rm.findAverageMinMax(result));
  }
}
